# Site settings
title: Boca Chica Brewing
slogan: The Brewery of Mars
email: hello@bocachicabrewing.com
url: https://bocachicabrewing.com
description: "Out-of-this-world craft beers engineered next door to the Starship Factory in Boca Chica, Texas."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Boca Chica Brewing

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:

  - title: instagram
    url: https://instagram.com/BocaChicaBrewing
  - title: facebook
    url: https://facebook.com/BocaChicaBrewing
  - title: twitter
    url: https://twitter.com/BocaChicaBrews

# Build settings
markdown: kramdown
permalink: pretty
